import type { CommandRule } from "./types.js";

export const SAFE_COMMANDS: ReadonlyArray<CommandRule> = [
  { cmd: "git" },
  { cmd: "node" },
  { cmd: "npm" },
  { cmd: "npx" },
  { cmd: "pnpm" },
  { cmd: "yarn" },
  { cmd: "bun" },
  { cmd: "python" },
  { cmd: "python3" },
  { cmd: "pip" },
  { cmd: "pip3" },
  { cmd: "poetry" },
  { cmd: "uv" },
  { cmd: "go" },
  { cmd: "cargo" },
  { cmd: "rustup" },
  { cmd: "make" },
  { cmd: "cmake" },
  { cmd: "docker" },
  { cmd: "docker-compose" },
  { cmd: "ls" },
  { cmd: "cat" },
  { cmd: "echo" },
  { cmd: "grep" },
  { cmd: "find" },
  { cmd: "sort" },
  { cmd: "uniq" },
  { cmd: "wc" },
  { cmd: "mkdir" },
  { cmd: "cp" },
  { cmd: "mv" },
  { cmd: "touch" },
  { cmd: "curl" },
  { cmd: "jq" },
  { cmd: "yq" },
];

export const SAFE_DOMAINS: readonly string[] = [
  "github.com",
  "*.github.com",
  "registry.npmjs.org",
  "pypi.org",
  "files.pythonhosted.org",
  "crates.io",
  "golang.org",
  "proxy.golang.org",
  "docker.io",
  "*.docker.io",
];

export const ALWAYS_DENY_PATHS: readonly string[] = [
  "~/.ssh/**",
  "~/.aws/**",
  "~/.gnupg/**",
  "~/.kube/config",
  "~/Library/Keychains/**",
  "~/.password-store/**",
];
